title: Lounge&lt;C++&gt;
baseurl: ""
url: "http://loungecpp.net"
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
exclude:
    - vendor
    - .travis.yml
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - Vagrantfile
defaults:
    -
        scope:
            path: ""
        values:
            layout: default
    -
        scope:
            path: "assets"
        values:
            layout: null
collections:
    cpp:
        output: true
        permalink: /cpp/:path/
    events:
        output: true
        permalink: /events/:path/
